
BEGIN;


CREATE TABLE IF NOT EXISTS public.pgosm_flex (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imported TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    osm_date date NOT NULL,
    region text NOT NULL,
    layerset TEXT NULL,
    srid text NOT NULL,
    pgosm_flex_version text NOT NULL,
    osm2pgsql_version text NOT NULL,
    "language" text NOT NULL,
    import_mode JSONB NULL,
    import_status TEXT NOT NULL DEFAULT 'Initializing',
    CONSTRAINT pk_osm_pgosm_flex PRIMARY KEY (id)
);

ALTER TABLE public.pgosm_flex
    DROP COLUMN IF EXISTS osm2pgsql_mode
;

ALTER TABLE public.pgosm_flex
    DROP COLUMN IF EXISTS osm2pgsql_replication;

ALTER TABLE public.pgosm_flex
    ADD COLUMN IF NOT EXISTS import_mode JSONB NULL;

ALTER TABLE public.pgosm_flex
    DROP COLUMN IF EXISTS import_uuid;

ALTER TABLE public.pgosm_flex
    ADD COLUMN IF NOT EXISTS import_status TEXT NOT NULL DEFAULT 'Initializing';

ALTER TABLE public.pgosm_flex
    ADD COLUMN IF NOT EXISTS layerset TEXT NULL;

ALTER TABLE public.pgosm_flex DROP COLUMN IF EXISTS project_url;
ALTER TABLE public.pgosm_flex DROP COLUMN IF EXISTS default_date;

COMMENT ON TABLE public.pgosm_flex IS 'Provides meta information on the PgOSM-Flex project including version and SRID used during the import. One row per import.';

COMMENT ON COLUMN public.pgosm_flex.imported IS 'Indicates when the import was ran.';
COMMENT ON COLUMN public.pgosm_flex.osm_date IS 'Indicates the date of the OpenStreetMap data loaded.  Recommended to set PGOSM_DATE env var at runtime, otherwise defaults to the date PgOSM-Flex was run.';
COMMENT ON COLUMN public.pgosm_flex.srid IS 'SRID of imported data.';
COMMENT ON COLUMN public.pgosm_flex.pgosm_flex_version IS 'Version of PgOSM-Flex used to generate schema.';
COMMENT ON COLUMN public.pgosm_flex.osm2pgsql_version IS 'Version of osm2pgsql used to load data.';
COMMENT ON COLUMN public.pgosm_flex.region IS 'Region specified at run time via env var PGOSM_REGION.';
COMMENT ON COLUMN public.pgosm_flex.language IS 'Preferred language specified at run time via env var PGOSM_LANGUAGE.  Empty string when not defined.';
COMMENT ON COLUMN public.pgosm_flex.layerset IS 'PgOSM Flex layerset used for the import style.';
COMMENT ON COLUMN public.pgosm_flex.import_status IS 'Status of the import. Starts as initialized, tracks status during imports and final success/failure.';


COMMIT;
