COMMENT ON TABLE public.amenity_point IS 'OpenStreetMap amenity points - all points with an amenity tag.  Some amenity tags are pulled into other tables (e.g. infrastructure, shop, and traffic layers) and duplicated again here. This is currently intentional but may change in the future. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/amenity.lua';
COMMENT ON TABLE public.amenity_line IS 'OpenStreetMap amenity lines - all lines with an amenity tag.  Some amenity tags are pulled into other tables (e.g. infrastructure, shop, and traffic layers) and duplicated again here. This is currently intentional but may change in the future. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/amenity.lua';
COMMENT ON TABLE public.amenity_polygon IS 'OpenStreetMap amenity polygons - all polygons with an amenity tag.  Some amenity tags are pulled into other tables (e.g. infrastructure, shop, and traffic layers) and duplicated again here. This is currently intentional but may change in the future. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/amenity.lua';


ALTER TABLE public.amenity_point
    ADD CONSTRAINT pk_osm_amenity_point_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE public.amenity_line
    ADD CONSTRAINT pk_osm_amenity_line_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE public.amenity_polygon
    ADD CONSTRAINT pk_osm_amenity_polygon_osm_id
    PRIMARY KEY (osm_id)
;


COMMENT ON COLUMN public.amenity_point.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN public.amenity_line.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN public.amenity_polygon.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';

COMMENT ON COLUMN public.amenity_point.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';
COMMENT ON COLUMN public.amenity_line.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';
COMMENT ON COLUMN public.amenity_polygon.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';

COMMENT ON COLUMN public.amenity_point.housenumber IS 'Value from addr:housenumber tag';
COMMENT ON COLUMN public.amenity_point.street IS 'Value from addr:street tag';
COMMENT ON COLUMN public.amenity_point.city IS 'Value from addr:city tag';
COMMENT ON COLUMN public.amenity_point.state IS 'Value from addr:state tag';
COMMENT ON COLUMN public.amenity_point.postcode IS 'Value from addr:postcode tag';

COMMENT ON COLUMN public.amenity_line.housenumber IS 'Value from addr:housenumber tag';
COMMENT ON COLUMN public.amenity_line.street IS 'Value from addr:street tag';
COMMENT ON COLUMN public.amenity_line.city IS 'Value from addr:city tag';
COMMENT ON COLUMN public.amenity_line.state IS 'Value from addr:state tag';
COMMENT ON COLUMN public.amenity_line.postcode IS 'Value from addr:postcode tag';

COMMENT ON COLUMN public.amenity_polygon.housenumber IS 'Value from addr:housenumber tag';
COMMENT ON COLUMN public.amenity_polygon.street IS 'Value from addr:street tag';
COMMENT ON COLUMN public.amenity_polygon.city IS 'Value from addr:city tag';
COMMENT ON COLUMN public.amenity_polygon.state IS 'Value from addr:state tag';
COMMENT ON COLUMN public.amenity_polygon.postcode IS 'Value from addr:postcode tag';

COMMENT ON COLUMN public.amenity_point.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN public.amenity_line.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN public.amenity_polygon.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';

COMMENT ON COLUMN public.amenity_point.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN public.amenity_line.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN public.amenity_polygon.geom IS 'Geometry loaded by osm2pgsql.';

COMMENT ON COLUMN public.amenity_point.address IS 'Address combined from address parts in helpers.get_address().';
COMMENT ON COLUMN public.amenity_line.address IS 'Address combined from address parts in helpers.get_address().';
COMMENT ON COLUMN public.amenity_polygon.address IS 'Address combined from address parts in helpers.get_address().';

COMMENT ON COLUMN public.amenity_point.osm_subtype IS 'Further describes osm_type for amenities.';
COMMENT ON COLUMN public.amenity_line.osm_subtype IS 'Further describes osm_type for amenities.';
COMMENT ON COLUMN public.amenity_polygon.osm_subtype IS 'Further describes osm_type for amenities.';

COMMENT ON COLUMN public.amenity_point.wheelchair IS 'Indicates if feature is wheelchair accessible. Values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';
COMMENT ON COLUMN public.amenity_line.wheelchair IS 'Indicates if feature is wheelchair accessible. Values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';
COMMENT ON COLUMN public.amenity_polygon.wheelchair IS 'Indicates if feature is wheelchair accessible. Values:  yes, no, limited.  Per https://wiki.openstreetmap.org/wiki/Key:wheelchair';

COMMENT ON COLUMN public.amenity_point.wheelchair_desc IS 'Value from wheelchair:description Per https://wiki.openstreetmap.org/wiki/Key:wheelchair:description';
COMMENT ON COLUMN public.amenity_line.wheelchair_desc IS 'Value from wheelchair:description Per https://wiki.openstreetmap.org/wiki/Key:wheelchair:description';
COMMENT ON COLUMN public.amenity_polygon.wheelchair_desc IS 'Value from wheelchair:description Per https://wiki.openstreetmap.org/wiki/Key:wheelchair:description';
