COMMENT ON TABLE public.natural_point IS 'OpenStreetMap natural points, e.g. trees, peaks, etc..  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';
COMMENT ON TABLE public.natural_line IS 'OpenStreetMap natural lines, e.g. cliffs, tree row, etc.. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';
COMMENT ON TABLE public.natural_polygon IS 'OpenStreetMap natural polygons, e.g. woods, grass, etc.. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';

COMMENT ON COLUMN public.natural_point.ele IS 'Elevation in meters';
COMMENT ON COLUMN public.natural_line.ele IS 'Elevation in meters';
COMMENT ON COLUMN public.natural_polygon.ele IS 'Elevation in meters';

ALTER TABLE public.natural_point
    ADD CONSTRAINT pk_osm_natural_point_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE public.natural_line
    ADD CONSTRAINT pk_osm_natural_line_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE public.natural_polygon
    ADD CONSTRAINT pk_osm_natural_polygon_osm_id
    PRIMARY KEY (osm_id)
;


COMMENT ON COLUMN public.natural_point.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN public.natural_line.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN public.natural_polygon.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';

COMMENT ON COLUMN public.natural_point.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';
COMMENT ON COLUMN public.natural_line.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';
COMMENT ON COLUMN public.natural_polygon.osm_type IS 'Stores the OpenStreetMap key that included this feature in the layer.';


COMMENT ON COLUMN public.natural_point.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN public.natural_line.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';
COMMENT ON COLUMN public.natural_polygon.name IS 'Best name option determined by helpers.get_name(). Keys with priority are: name, short_name, alt_name and loc_name.  See pgosm-flex/flex-config/helpers.lua for full logic of selection.';

COMMENT ON COLUMN public.natural_point.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN public.natural_line.geom IS 'Geometry loaded by osm2pgsql.';
COMMENT ON COLUMN public.natural_polygon.geom IS 'Geometry loaded by osm2pgsql.';
